#%RAML 1.0 NamedExample

  [
     { 
       "category_id": 11,
       "category_name": "laptops"
      },
      {
        "category_id": 12,
        "category_name": "home electronics"
      },
      {
         "category_id": 13,
         "category_name": "mouse" 
      },
      {
        "category_id": 14,
        "category_name": "mobile accessories"  
      },
             
      {
        "category_id": 15,
        "catgory_name": "laptop skins"  
      }
         
  ]
    



