#%RAML 1.0 NamedExample

[     
  {
    "product_id": 3,
    "product_name": "HP",
    "description": "core I7",
    "video_url": "www.hp.com",
    "category_id": 15,    
    "price": 7000
  },               
  {
    "product_id": 11,
    "product_name": "DELL",
    "description": "core I5",
    "video_url": "www.dell.com",
    "category_id": 15,
    "price": 5000 
    }
  ]
