#%RAML 1.0 DataType
type: object
properties:
  orderId:
    type: integer
    required: false
  userId:
    type: integer
  order_name:
    type: string
  order_date:
    type: string
  order_status:
    type: string
 
  


 