#%RAML 1.0 ResourceType
post:
  description: Add a new <<resourcePathName | !singularize >> to <<resourcePathName>>
  responses:
    201:
      body:
        application/json:
          example:
            <<exampleReference1>>
