#%RAML 1.0 NamedExample
[
  {
  "categoryid": 11,
  "name": "laptops"

  },
  {
    "categoryid": 12,
  "name": "mobile accessory" 
  },
  {
    "categoryid": 13,
  "name": "mouse" 
  },
  {
     "categoryid": 14,
  "name": "home electronics"
  },
  {
     "categoryid": 15,
  "name": "womens clothing"
  },
  {
    "categoryid": 16,
  "name": "mens clothing" 
  },
  {
     "categoryid": 17,
  "name": "gaming geeks"
  },
  {
     "categoryid": 18,
  "name": "laptop cover"
  },
  {
     "categoryid": 19,
  "name": "laptop skins"
  },
  {
     "categoryid": 20,
  "name": "study buddy"
  }
  ]