#%RAML 1.0 NamedExample

   [
                {
                "productid": 1,
                "catagoryid":13,
                "name": hp,
                "description":core i 7,
                "video_url": "www.hp.com",
                "price": 7000

              },{
                 "productid": 2,
                "catagoryid":15,
                "name": dell,
                "description":core i 5,
                "video_url": "www.dell.com",
                "price": 5000

              }
     

              ]