#%RAML 1.0 NamedExample

  {
                "productid": 1,
                "catagoryid":13,
                "name": hp,
                "description":core i 7,
                "video_url": "www.hp.com",
                "price": 7000

              }